name: Check app status

on: workflow_dispatch

env:
  PACKAGES: "com.cacostar.evilprank com.example.app2 com.example.app3"

jobs:
  check_app_status:
    runs-on: ubuntu-latest
    steps:
    - name: Load package names
      run: echo "PACKAGES=\"$PACKAGES\"" >> $GITHUB_ENV

    - name: Check google-play-scraper command
      run: |
        which google-play-scraper
        google-play-scraper --version

    - name: Check app status
      run: |
        for package in $PACKAGES; do
          status=$(google-play-scraper $package | jq -r '.[0].status')
          if [[ "$status" != "SUCCESS" ]]; then
            echo "Error: $package is not published. Status: $status"
          else
            echo "Package: $package"
            echo "Status: $status"
          fi
        done
