name: Check app status

on:
  workflow_dispatch

env:
  PACKAGES: "com.cacostar.evilprank com.example.app2 com.example.app3"

jobs:
  check_app_status:
    runs-on: ubuntu-latest
    steps:
    - name: Check app status
      run: |
        for package in $PACKAGES; do
          # Get the app details page HTML
          html=$(curl -sL "https://play.google.com/store/apps/details?id=$package")
    
          # Parse the HTML to get the app status, update time, and version
          status=$(echo "$html" | grep -oP '(?<=data-test-server-message=")Published(.*?)(?=")')
          updated=$(echo "$html" | grep -oP '(?<=class="htlgb"><span class="htlgb">Updated</span></div><div class="IQ1z0d"><span class="htlgb">)(.*?)(?=</span></div></div><div class="xSyT2c">)')
          version=$(echo "$html" | grep -oP '(?<=class="BgcNfc">)(.*?)(?=</span><span class="htlgb">)')
    
          # Print the app status, update time, and version
          if [[ "$status" == "Published" ]]; then
            echo "Package: $package"
            echo "Status: $status"
            echo "Last updated: $updated"
            echo "Version: $version"
          else
            echo "Error: $package is not published. Status: $status"
          fi
        done
