name: Check Play Store
on:
  schedule:
    - cron: '* * * * *'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs
          sudo apt-get install -y npm
          npm install -g google-play-scraper
          sudo apt-get install -y jq

      - name: Load package names
        run: |
          PACKAGES="com.cacostar.evilprank com.example.app2 com.example.app3"

      - name: Check app status
        run: |
          for package in $PACKAGES; do
            status=$(google-play-scraper $package | jq '.[0].status')
            echo "$package: $status"
          done

      - name: Complete workflow
        run: echo "App status check complete."
