name: Check app status

on:
  workflow_dispatch

env:
  PACKAGES: "com.example.app1 com.example.app2 com.example.app3"

jobs:
  check_app_status:
    runs-on: ubuntu-latest
    steps:
      - name: Install google-play-crawler
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          sudo npm install -g google-play-crawler

      - name: Check app status
        run: |
          for package in $PACKAGES; do
            status=$(google-play-crawler -p $package | jq -r '.status')
            if [[ "$status" != "OK" ]]; then
              echo "Error: $package is not published. Status: $status"
            else
              last_update=$(google-play-crawler -p $package | jq -r '.lastUpdated')
              version=$(google-play-crawler -p $package | jq -r '.version')
              echo "Package: $package"
              echo "Status: $status"
              echo "Last Updated: $last_update"
              echo "Version: $version"
            fi
          done
